particlesJS("particles-js",{
    "particles":{
      "number":{
        "value":130,//紙吹雪の数
        "density":{
          "enable":false,
          "value_area":400
        }
      },
      "color": {
          "value": ["#ffffff", "#dc143c"]
      },
      "shape":{
        "type":"polygon",
        "stroke":{
          "width":0,
        },
        "polygon":{
          "nb_sides":5//角の数
        }
        },
        "opacity":{
          "value":1,
          "random":false,
          "anim":{
            "enable":true,
            "speed":20,
            "opacity_min":0,
            "sync":false
          }
        },
        "size":{
          "value":5.305992965476349,
          "random":true,//サイズをランダム
          "anim":{
            "enable":true,
            "speed":1.345709068776642,
            "size_min":0.8,
            "sync":false
          }
        },
        "line_linked":{
          "enable":false,
        },
        "move":{
          "enable":true,
        "speed":5,//動きの速さ
        "direction":"bottom",
        "random":true,//動きはランダム
        "straight":false,//動きをとどめない
        "out_mode":"out",//画面の外に出るように
        "bounce":false,//跳ね返りなし
          "attract":{
            "enable":false,
            "rotateX":600,
            "rotateY":1200
          }
        }
      },
      "interactivity":{
        "detect_on":"canvas",
        "events":{
          "onhover":{
            "enable":false,
          },
          "onclick":{
            "enable":false,
          },
          "resize":true
        },
      },
      "retina_detect":true
    });